name: Generate and Deploy True M3U8 Files

on:
  push:
    paths:
      - 'ytm3u8/*.strm'
  workflow_dispatch:

jobs:
  generate-m3u8:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write
    
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_FULL_ACCESS }}
          fetch-depth: 0  # Important for git operations later

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Create working directory
        run: |
          mkdir -p ytm3u8/M3U8
          mkdir -p pages_deploy

      - name: Generate valid M3U8 files
        run: |
          cd ytm3u8
          for strm_file in *.strm; do
            if [ -f "$strm_file" ]; then
              base_name=$(basename "$strm_file" .strm)
              hls_url=$(cat "$strm_file")
              echo -e "#EXTM3U\n#EXTINF:-1,$base_name\n$hls_url" > "M3U8/${base_name}.m3u8"
              echo -e "#EXTM3U\n#EXTINF:-1,$base_name\n$hls_url" > "../pages_deploy/${base_name}.m3u8"
            fi
          done

      - name: Create CORS configuration files
        run: |
          echo "/*.m3u8
  Content-Type: application/vnd.apple.mpegurl
  Access-Control-Allow-Origin: *
  Access-Control-Allow-Methods: GET
  Access-Control-Expose-Headers: Content-Type" > pages_deploy/_headers

          echo "/* /index.html 200" > pages_deploy/_redirects

      - name: Validate M3U8 files
        run: |
          cd pages_deploy
          for m3u8_file in *.m3u8; do
            echo "Validating $m3u8_file..."
            if ! grep -q "#EXTM3U" "$m3u8_file"; then
              echo "ERROR: $m3u8_file is not a valid M3U8 file!"
              exit 1
            fi
          done

      - name: Upload artifact for GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: pages_deploy/

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

      - name: Commit M3U8 files to main branch
        if: github.event_name == 'push'
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add ytm3u8/M3U8
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "Auto-update M3U8 files"
            git push origin HEAD:main
          else
            echo "No changes to commit"
          fi
