name: Generate M3U8 Redirects
on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  generate-redirects:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout IPTV repo (public)
      uses: actions/checkout@v4
      with:
        path: IPTV
        
    - name: Checkout ytm3u8 repo (private)
      uses: actions/checkout@v4
      with:
        repository: 858it-cast/ytm3u8
        token: ${{ secrets.PAT_FULL_ACCESS }}  # MODIFICARE QUESTO
        path: ytm3u8
        fetch-depth: 0
        
    - name: Debug listing
      run: ls -laR ytm3u8/  # Verifica il contenuto
        
    - name: Create redirect files
      run: |
        mkdir -p IPTV/ytm3u8
        
        if ls ytm3u8/YouTubeLive/*.m3u8 >/dev/null 2>&1; then
          for m3u8_file in ytm3u8/YouTubeLive/*.m3u8; do
            filename=$(basename "$m3u8_file")
            url=$(head -n 1 "$m3u8_file")
            
            echo "$url" > "IPTV/ytm3u8/${filename%.*}.strm"
            
            echo "#EXTM3U" > "IPTV/ytm3u8/$filename"
            echo "$url" >> "IPTV/ytm3u8/$filename"
          done
        else
          echo "##[error]Nessun file .m3u8 trovato!"
          exit 1
        fi
        
    - name: Commit changes
      run: |
        cd IPTV
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add ytm3u8/
        git commit -m "Update redirects $(date +'%Y-%m-%d %H:%M')" || echo "Nessuna modifica da commitare"
        git push
