name: Generate M3U8 Redirects
on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  generate-redirects:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout IPTV repo (public)
      uses: actions/checkout@v4
      with:
        path: IPTV
        
    - name: Checkout ytm3u8 repo (private)
      uses: actions/checkout@v4
      with:
        repository: 858it-cast/ytm3u8  # Sostituisci con il tuo username reale
        token: ${{ secrets.ACCESS_TOKEN }}  # Deve corrispondere al nome del secret
        path: ytm3u8
        fetch-depth: 0
        
    - name: Create redirect files
      run: |
        mkdir -p IPTV/ytm3u8
        
        if ls ytm3u8/YouTubeLive/*.m3u8 >/dev/null 2>&1; then
          for m3u8_file in ytm3u8/YouTubeLive/*.m3u8; do
            filename=$(basename "$m3u8_file")
            url=$(head -n 1 "$m3u8_file")
            
            # Crea file .strm
            echo "$url" > "IPTV/ytm3u8/${filename%.*}.strm"
            
            # Crea file .m3u8 di redirect
            echo "#EXTM3U" > "IPTV/ytm3u8/$filename"
            echo "$url" >> "IPTV/ytm3u8/$filename"
          done
        else
          echo "Nessun file .m3u8 trovato in ytm3u8/YouTubeLive/"
          ls -laR ytm3u8/
          exit 1
        fi
        
    - name: Commit and push changes
      run: |
        cd IPTV
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        
        git add ytm3u8/
        if [ -n "$(git status --porcelain)" ]; then
          git commit -m "Auto-update M3U8 redirects [$(date +'%Y-%m-%d %H:%M:%S')]"
          git push
        else
          echo "Nessuna modifica da commitare."
        fi
