name: Generate M3U8 Redirects
on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  generate-redirects:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout IPTV repo
      uses: actions/checkout@v4
      with:
        path: IPTV
        
    - name: Checkout ytm3u8 repo (private)
      uses: actions/checkout@v4
      with:
        repository: your-username/ytm3u8
        token: ${{ secrets.PAT_TOKEN }}  # Deve essere un token con accesso al repo privato
        path: ytm3u8
        # Aggiungi queste opzioni per evitare errori
        fetch-depth: 0
        persist-credentials: true
        
    - name: Create redirect files
      run: |
        # Crea directory se non esiste
        mkdir -p IPTV/ytm3u8
        
        # Verifica che i file siano presenti
        if [ ! -d "ytm3u8/YouTubeLive" ]; then
          echo "Errore: Directory ytm3u8/YouTubeLive non trovata!"
          ls -R ytm3u8/
          exit 1
        fi
        
        # Processa i file .m3u8
        for m3u8_file in ytm3u8/YouTubeLive/*.m3u8; do
          if [ -f "$m3u8_file" ]; then
            filename=$(basename "$m3u8_file")
            url=$(head -n 1 "$m3u8_file")
            
            # Crea file .strm
            echo "$url" > "IPTV/ytm3u8/${filename%.*}.strm"
            
            # Crea file .m3u8 di redirect
            echo "#EXTM3U" > "IPTV/ytm3u8/$filename"
            echo "$url" >> "
