name: Deploy IPTV M3U8 with GitHub Pages

on:
  push:
    paths:
      - 'ytm3u8/*.strm'
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Generate M3U8 Files
        run: |
          import os
          import pathlib
          
          # Crea directory di output
          output_dir = pathlib.Path('m3u8_output')
          output_dir.mkdir(exist_ok=True)
          
          # Processa tutti i file .strm
          for strm_file in pathlib.Path('ytm3u8').glob('*.strm'):
              channel_name = strm_file.stem
              hls_url = strm_file.read_text().strip()
              
              # Crea contenuto M3U8 valido
              m3u8_content = f"""#EXTM3U
#EXTINF:-1 tvg-id="{channel_name}",{channel_name}
{hls_url}"""
              
              # Scrivi file di output
              (output_dir / f"{channel_name}.m3u8").write_text(m3u8_content)

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'm3u8_output/'
          retention-days: 1

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
