name: IPTV M3U8 Auto-Updater

on:
  push:
    paths:
      - 'ytm3u8/*.strm'
  workflow_dispatch:
  schedule:
    - cron: '*/30 * * * *'

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  generate-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v
