name: Convert .strm to .m3u8 with raw.githack

on:
  push:
    paths:
      - 'ytm3u8/*.strm'
  workflow_dispatch:

jobs:
  generate-m3u8:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_FULL_ACCESS }}

      - name: Create M3U8 directory
        run: mkdir -p ytm3u8/M3U8

      - name: Generate .m3u8 files
        run: |
          cd ytm3u8
          for strm_file in *.strm; do
            if [ -f "$strm_file" ]; then
              base_name=$(basename "$strm_file" .strm)
              echo "https://raw.githack.com/$GITHUB_REPOSITORY/main/ytm3u8/${base_name}.strm" > "M3U8/${base_name}.m3u8"
            fi
          done

      - name: Remove obsolete .m3u8 files
        run: |
          cd ytm3u8
          if [ -d "M3U8" ]; then
            cd M3U8
            for m3u8_file in *.m3u8; do
              base_name=$(basename "$m3u8_file" .m3u8)
              if [ ! -f "../${base_name}.strm" ]; then
                rm "$m3u8_file"
              fi
            done
          fi

      - name: Commit and push changes
        run: |
          cd ytm3u8
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add M3U8
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "Auto-update M3U8 links"
            git push
          else
            echo "No changes to commit"
          fi
