name: Convert .strm to raw.githack .m3u8 Links

on:
  push:
    paths:
      - 'ytm3u8/*.strm'  # Monitora solo i file .strm nella root di ytm3u8
  workflow_dispatch:      # Permite esecuzione manuale

jobs:
  generate-m3u8:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Crea cartella M3U8
        run: mkdir -p ytm3u8/M3U8

      - name: Genera file .m3u8 con link raw.githack
        run: |
          cd ytm3u8
          for strm_file in *.strm; do
            if [ -f "$strm_file" ]; then
              base_name=$(basename "$strm_file" .strm)
              echo "https://raw.githack.com/$GITHUB_REPOSITORY/main/ytm3u8/${base_name}.strm" > "M3U8/${base_name}.m3u8"
            fi
          done

      - name: Elimina file .m3u8 obsoleti (se lo .strm è stato rimosso)
        run: |
          cd ytm3u8/M3U8
          for m3u8_file in *.m3u8; do
            base_name=$(basename "$m3u8_file" .m3u8)
            if [ ! -f "../${base_name}.strm" ]; then
              rm "$m3u8_file"
              echo "Rimosso ${m3u8_file} (file .strm mancante)"
            fi
          done

      - name: Commit e push delle modifiche
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add ytm3u8/M3U8
          git commit -m "Auto-generate M3U8 links via raw.githack"
          git push
