name: Convert .strm to .m3u8 with raw.githack

on:
  push:
    paths:
      - 'ytm3u8/*.strm'
  workflow_dispatch:

jobs:
  generate-m3u8:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Necessario per fare push
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_FULL_ACCESS }}  # Usa il token automatico

      - name: Crea cartella M3U8
        run: mkdir -p ytm3u8/M3U8

      - name: Genera file .m3u8
        run: |
          cd ytm3u8
          for strm_file in *.strm; do
            if [ -f "$strm_file" ]; then
              base_name=$(basename "$strm_file" .strm)
              echo "https://raw.githack.com/$GITHUB_REPOSITORY/main/ytm3u8/${base_name}.strm" > "M3U8/${base_name}.m3u8"
            fi
          done

      - name: Elimina file obsoleti
        run: |
          cd ytm3u8/M3U8
          for m3u8_file in *.m3u8; do
            base_name=$(basename "$m3u8_file" .m3u8)
            if [ ! -f "../${base_name}.strm" ]; then
              rm "$m3u8_file"
            fi
          done

      - name: Commit e Push
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add M3U8
          git commit -m "Auto-update M3U8 links"
          git push
