name: Sync M3U8 Redirects

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:
  repository_dispatch:
    types: [trigger-sync]

jobs:
  generate_redirects:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
      - name: Checkout IPTV repo
        uses: actions/checkout@v4

      - name: Checkout private ytm3u8 repo
        uses: actions/checkout@v4
        with:
          repository: 858it-cast/ytm3u8
          token: ${{ secrets.ACCESS_TOKEN }}  # MODIFICARE QUI
          path: ytm3u8-files
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Create redirect endpoints
        run: |
          mkdir -p hls-redirects
          
          if [ ! -d "ytm3u8-files/YouTubeLive" ]; then
            echo "##[error]Directory ytm3u8-files/YouTubeLive not found!"
            exit 1
          fi

          for m3u8_file in ytm3u8-files/YouTubeLive/*.m3u8; do
            [ ! -f "$m3u8_file" ] && continue
            filename=$(basename "$m3u8_file")
            hls_url=$(cat "$m3u8_file")
            
            cat <<EOF > "hls-redirects/${filename}"
            <!DOCTYPE html>
            <script>
              const url = "$hls_url";
              const headers = new Headers({
                'Content-Type': 'application/vnd.apple.mpegurl',
                'Access-Control-Allow-Origin': '*'
              });
              fetch(url)
                .then(response => response.text())
                .then(data => {
                  const response = new Response(data, { headers });
                  self.postMessage(response, '*');
                });
            </script>
            EOF
          done
          
          echo "/*.m3u8" > hls-redirects/_headers
          echo "  Content-Type: application/vnd.apple.mpegurl" >> hls-redirects/_headers
          echo "  Access-Control-Allow-Origin: *" >> hls-redirects/_headers

      - name: Configure Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: hls-redirects

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4

      - name: Update timestamp
        run: |
          date > last_update.txt
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add last_update.txt
          git commit -m "Update redirects timestamp [skip ci]" || exit 0
          git push
