name: Sync M3U8 Redirects

on:
  schedule:
    - cron: '0 * * * *'  # Run hourly
  workflow_dispatch:
  repository_dispatch:
    types: [trigger-sync]

jobs:
  generate_redirects:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
      - name: Checkout IPTV repo
        uses: actions/checkout@v4

      - name: Checkout private ytm3u8 repo
        uses: actions/checkout@v4
        with:
          repository: 858it-cast/ytm3u8
          token: ${{ secrets.ACCESS_TOKEN }}
          path: ytm3u8-files
          fetch-depth: 0

      - name: Verify files
        run: |
          ls -la ytm3u8-files/YouTubeLive/
          [ ! -d "ytm3u8-files/YouTubeLive" ] && echo "##[error]YouTubeLive directory not found!" && exit 1

      - name: Create redirect endpoints
        run: |
          mkdir -p hls-redirects
          
          for m3u8_file in ytm3u8-files/YouTubeLive/*.m3u8; do
            [ ! -f "$m3u8_file" ] && continue
            filename=$(basename "$m3u8_file")
            hls_url=$(cat "$m3u8_file")
            
            # Generate minimal HTML with JS redirect
            cat > "hls-redirects/${filename}" <<EOF
            <!DOCTYPE html>
            <script>
              window.location.href = "$hls_url";
            </script>
            EOF
          done

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v3

      - name: Upload to Pages
        uses: actions/upload-pages-artifact@v2
        with:
          path: hls-redirects

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
